name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:



  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16        
    
    - name: Vet
      run: go vet -v ./...
      working-directory: ./postgres

    - name: Test
      run: go test -v ./...
      working-directory: ./postgres

      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        HTTP_PORT: 5050
        JWT_KEY: wqGyEBBfPK9w3Lxw
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DATABASE: postgres
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
